### ISSUE TITLE
Create UUIDv7 from timestamp?

### ISSUE THREAD

**Issue by Bouke** [medo64/Medo.Uuid7#10]
UUID v7's would be great for 'database locality', assuming tuples created around the same time are often also consumed at the same time. This means the database will need to load less pages to retrieve all tuples for a query. In order to have UUID's created for historic records, it would be nice to support generating UUID's with a predefined timestamp; e.g. `new Uuid7(DateTime(Offset) timestamp)`. What do you think of this?

**Comment by medo64** [comment]
Problem is making this compatible with current mechanisms to resolve monotonicity and its error checking (e.g. to prevent rollbacks). Implementing this as a one-shot UUID creation (the only way as not to impact performance or monotonicity properties) would make UUIDs generated as such have slightly less collision resistance.

I need to think about it a bit and I might add this method but, if it comes, it will contain bunch of warnings in documentation. :)

**Comment by Bouke** [comment]
Thanks. `Uuid7.FromGuid()` also doesn't have such error checking I think; so it would be rather similar to that API in terms of guarantees?

For my use-case I think the procedure below will get me a long way:

```c#
Guid CreateUuid7(DateTimeOffset offset)
{
    var bytes = Uuid7.NewGuid().ToByteArray();
    var ms = offset.ToUnixTimeMilliseconds();
    bytes[0] = (byte)(ms >> 40);
    bytes[1] = (byte)(ms >> 32);
    bytes[2] = (byte)(ms >> 24);
    bytes[3] = (byte)(ms >> 16);
    bytes[4] = (byte)(ms >> 8);
    bytes[5] = (byte)ms;
    return new Guid(bytes);
}
```

**Comment by medo64** [comment]
Yeah, that sounds reasonable. I will figure the exact syntax over weekend and I definitely want to include counter too.

**Comment by medo64** [comment]
Ok, for starters I've decided to do this with `Fill` and `NewUuid7` methods.

Examples:
```
var timestamp = DateTimeOffset.UtcNow;

var uuid = Uuid7.NewUuid7(timestamp);  // single UUID

var uuids = new Uuid7[10000];
Uuid7.Fill(uuids, timestamp);  // many UUID
```

Code has been added as part of commit #02bd0aa.
It will be part of the next release.
