### ISSUE TITLE
Suggestion: static method to generate Guid v7? + EFCore integration

### ISSUE THREAD

**Issue by dariogriffo** [medo64/Medo.Uuid7#2]
First of all: loving this project to extend Guids to v7 proposal.
Benchmarks on Postgres are stunning!
Linear inserts time with EFCore ~8.5secs per 1 million.
So, being said this, would you be open for me to create 2 PRs:
- Create a new extension method to generate Guid without creating a Uuid7 first? 
```csharp
Uuid7.NewGuid()
```
- Add a new nuget package to integrate with EFCore?

I have both ready, but want to know your thoughts

**Comment by medo64** [comment]
I am definitelly ok with NewGuid portion. That would be a really good helper method.

As for EFCore integration, you need to help me there since I am not playing with EF these days. Why the existing [Nuget package](https://www.nuget.org/packages/Medo.Uuid7) cannot be integrated there?

**Comment by dariogriffo** [comment]
You defined a new data type and efcore doesn't know how to serialize it. EfCore works with native types, other convertions have to made explicit.
If you are ok you can you create an empty repository called
Medo.Uuid7.EntityFrameworkCore
And I will push the code then you can push the package.
I suggest this because the current folder structure is not aligned to have multiple projects and you can also iterate them separated.

**Comment by dariogriffo** [comment]
This is th efcore code but you definitely want a separate package for consumers that won't use efcore 

```csharp
public class Uuid7ToBytesConverter : ValueConverter<Uuid7, byte[]>
{
    private static readonly ConverterMappingHints defaultHints = new ConverterMappingHints(size: 16);

    public UlidToBytesConverter()
        : base(
                convertToProviderExpression: x => x.ToByteArray(),
                convertFromProviderExpression: x => new Uuid7(x),
                mappingHints: defaultHints)
    {
    }
}
```

**Comment by medo64** [comment]
Ok, I've created a new [Medo.Uuid7.EntityFrameworkCore](https://github.com/medo64/Medo.Uuid7.EntityFrameworkCore) repository. That way you can push your code and I can try to understand it. :)

I agree that keeping EF stuff in a separate package would be the best albeit I am not sure I like the idea of a separate repository as it will make code maintenance a bit more problematic.

At this time I am toying with an idea of simply refactoring my directory structure of this repository to include EF stuff as a separate project, with a separate README, package, etc. With a few conditional compilation constants, majority of code would be still shared while having a different code path for what I expect will be a small difference.

**Comment by dariogriffo** [comment]
If can create that PR on this repo if that's ok?

**Comment by medo64** [comment]
> If can create that PR on this repo if that's ok?

Sure

**Comment by dariogriffo** [comment]
I need a branch in that repo to make a fork. Can you just add an empty README file please?
I have the code ready for the new repo.
I kept the same structure as you created this repo, basically replacing `Medo.Uuid7` with `Medo.Uuid7.EntityFrameworkCore` and coded with the style guidelines.
Test project is using sqlite
An screenshot of how is working on postgres


![image](https://github.com/medo64/Medo.Uuid7/assets/3247183/106b399a-c277-49df-95fd-6fa29117419a)

**Comment by medo64** [comment]
Can you push it to Medo.Uuid7 (i.e. the same repo). I have a separate `efcore` branch there. Just push all code as you have it and I'll merge it afterward.

**Comment by medo64** [comment]
Merge has been completed (albeit in the main branch as I did incorrect pull).
I've noticed there are XML comments missing for Uuid7To*Converter classes. Can you add those (new pull request)?

**Comment by dariogriffo** [comment]
I can't load the solution correctly because it has conditional symbols.
Can you create a standard .net solution layout to work?

**Comment by medo64** [comment]
Try installing .NET framework 6 and .NET 4.8 in Visual Studio - that usually helps.
Conditional compiles should load ok in Visual Studio (I am using Community edition).

**Comment by dariogriffo** [comment]
I don't use windows, I code on [rider] on Debian, since your project targets netstandard2 and net6+ I decided to contribute.
Sorry for the inconvenience.
The sad reality is that the layout of the folders you created is not compatible with the new .net way of working with csproj file.
From some time now, csproj files load every file in the same directory and have internal rules on how to handle them. That's why when you create something with the dotnet cli everything goes to foldersI can create the EfCore project and pusht the nuget as my own referencing Meedo.Uuid7, that's another option

**Comment by medo64** [comment]
Hm, I use VS Code under Linux and dotnet actually handles this ok.
However, I can also make separate projects for each framework to make it easier on other.

Since I don't have Rider, you'll need to teach me a bit. Can Rider handle having multiple project files in the same directory or is having each project file in a separate directory a hard requirement?

**Comment by medo64** [comment]
I installed Rider on my machine (Ubuntu 23.04) and opened solution file for EFCore and it compiles ok.
However, on my side I have both .NET 6 and .NET 7 installed. Could it be that issue is due to missing framework?
Can you share what error you have?

Worst case scenario, I will just create a separate project to for each platform (albeit I do need to keep the current ones due to how I have Nuget's multi-framework setup).

**Comment by medo64** [comment]
I've refactored projects to have only a single target, hopefuly that helps with Rider.
It's in branch [ridertest](https://github.com/medo64/Medo.Uuid7/tree/ridertest) and solution file has -net60 suffix. Please check if that works for you.
