### ISSUE TITLE
Add convenience method/property to obtain a UUIDv7's timestamp

### ISSUE THREAD

**Issue by QuantumToasted** [medo64/Medo.Uuid7#7]
Hi there - Really looking forward to using this library rather than any attempt at rolling my own...to my understanding, UUIDv7's data structure contains a Unix timestamp in milliseconds - It would be nice to have a property or method available to obtain this as a `DateTime` or `DateTimeOffset`, whichever is preferred - I tried perusing the source code and found no such properties or methods, so hopefully I'm not just missing something. I'm using UUIDv7s as generated IDs for a project I'm working on and would like to have a simple way to communicate when it was generated to the user.

**Comment by medo64** [comment]
Added both ToDateTime() and ToDateTimeOffset() methods.
As expected, they only work when dealing with UUID v7 variant.
Supported as of v1.8.2.
